# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: nandant@gmail.com
brand: Coding Nomad
headline: Adventure may hurt you but monotony will kill you!
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "/coding-nomad" # the subpath of your site, e.g. /blog
url: "https://nthakur20.github.io" # the base hostname & protocol for your site
copyright: 2019 Nandan Thakur, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: nandant@gmail.com
phone: +91-7767012929

# Tracking
googleAnalitycsID: UA-83933844-1

